[WIP] BIP155 `getaddrv2` and `addrv2`
MetacoSA/NBitcoin pull request #940
Opened 2020-11-16 20:13 UTC by lontivero

Since September 15th Tor started warning onion service operators that v2 is deprecated. In part because of that Bitcoin Core has merged [PR 19954](https://github.com/bitcoin/bitcoin/pull/19954) that implements [BIP155 addrv2 message](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki). The new p2p messages allow share nodes' endpoints other than ip:port (onion v3, I2P, etc).

Currently Wasabi connects to third-party nodes through v2 onion services only because v2 addresses can be encoded as IPv6 addresses (onioncat) what makes the connection transparent because it is the tor client the one that knows how to solve the real onion address.

After onion services v2 are completely removed Wasabi will not be able to connect to third-party nodes any more.
 
### This PR includes some WIP code that:

* adds `getaddrv2` and `addrv2` p2p messages.
* adds SHA3 digest (the `NBitcoin.Altcoins` contains an implementation but moving that it is a big change)
* adds code to keep backward compatibility.

### Problems

The p2p code in NBitcoin uses `IPEndpoint` in many places and it seems we have to use the `NetworkAddress` instead and also know when it needs to use a proxy.

Any commment, suggestion, clue or whatever that could help me to implement this is very much welcome.

2020-11-17 08:56 UTC, nopara73 commented
@lontivero In Wasabi we're using `EndPoint`
![image](https://user-images.githubusercontent.com/9156103/99367876-cccdce80-28ba-11eb-86b2-e26b44eec4ee.png) for local Bitcoin Core P2P connections: IIRC people were pasting onion addresses there and report it still works.

For backend connection we're using `Uri`.

Anyway if your solution works, then whatever I just wanted to note this.

2020-11-30 04:20 UTC, NicolasDorier commented
@nopara73 In NBitcoin we use Endpoint as well and `TryParseEndpoint` to parse it. (which support onion already)

2020-12-03 10:18 UTC, molnard requested changes

2020-12-03 10:18 UTC, molnard commented on NBitcoin.Tests/ProtocolTests.cs
> +			CancellationTokenSource cts = new CancellationTokenSource(5000 * 100);
Dispose

2020-12-03 10:18 UTC, molnard commented on NBitcoin/Protocol/NetworkAddress.cs
> +		public bool IsTOR => (Network)network == Network.Onion;
IsTor

2020-12-07 10:11 UTC, nopara73 commented
@lontivero You should be able to make it ready for review (non-draft) since https://github.com/MetacoSA/NBitcoin/pull/944 is merged, right?

2020-12-08 15:50 UTC, lontivero commented
Yes. I am trying to make it no so big. Also, sipa changed bitcoin core (it is not merged yet) making this PR incompatible, this means that I cannot use the rc2 to test this, I need to compile core and use that.

2020-12-08 20:37 UTC, lontivero commented
@nopara73 @NicolasDorier this is ready for review (the failing test is failing for some unrelated reason).

After this PR I need to make a few small changes like signaling `sendaddrv2` before `VerAck` message (this changes the order of the handshake messages), clean up a few duplicated code, increase the protocol version to 70016 and make sure Tor addresses are routed through Tor (I didn't check it).

2020-12-09 13:25 UTC, NicolasDorier commented
Please do not change types around, that's too much breaking changes.
Keep `NetworkAddress`, I don't understand what `Service` is.
You can modify `NetworkAddress` to support your changes.

Do not change the IPEndpoint stuff in Node class. Keep the current behavior for what is not Torv3, if it is Torv3 then just throw an exception like InvalidOperationException.

2020-12-09 16:54 UTC, lontivero commented
Copied. I will implement everything in `NetworkAddress` then and avoid changes in `Node`. I am closing this PR and I will open other/s.

2020-12-09 16:54 UTC, closed without merging